//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBQCode.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Coop {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Coop() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BBQCode.Resources.Coop", typeof(Coop).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Cooperative.
        /// </summary>
        public static string ContentTitle {
            get {
                return ResourceManager.GetString("ContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Research and Development.
        /// </summary>
        public static string JobAlexisLerouxChartre {
            get {
                return ResourceManager.GetString("JobAlexisLerouxChartre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Ninja, Fifth Dan.
        /// </summary>
        public static string JobElicNg {
            get {
                return ResourceManager.GetString("JobElicNg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain Chief of the Internets.
        /// </summary>
        public static string JobMartinFournier {
            get {
                return ResourceManager.GetString("JobMartinFournier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Wizardry Operator.
        /// </summary>
        public static string JobSamuelPare {
            get {
                return ResourceManager.GetString("JobSamuelPare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor of Informative Information.
        /// </summary>
        public static string JobSimonGodbout {
            get {
                return ResourceManager.GetString("JobSimonGodbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Members.
        /// </summary>
        public static string MembersTitle {
            get {
                return ResourceManager.GetString("MembersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coop: Our mission, our team..
        /// </summary>
        public static string MetaDescription {
            get {
                return ResourceManager.GetString("MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bacon ipsum dolor sit amet jerky meatloaf boudin short ribs, beef ham..
        /// </summary>
        public static string MissionQuote {
            get {
                return ResourceManager.GetString("MissionQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lacus nunc, tincidunt ac viverra et, eleifend blandit turpis. Etiam tempor tortor at sapien ullamcorper eget semper erat tempus. Aliquam magna tellus, sollicitudin quis faucibus non, sagittis nec arcu. Ut tincidunt congue erat eu luctus..
        /// </summary>
        public static string MissionText1 {
            get {
                return ResourceManager.GetString("MissionText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer et est massa, in tristique tortor. Curabitur viverra congue est et vestibulum. Donec nec aliquet mauris. Etiam vulputate mauris a libero bibendum sed pharetra libero tincidunt. Cras lacus massa, laoreet sed laoreet eget, tincidunt nec ipsum. Nam mattis vestibulum blandit. In hac habitasse platea dictumst..
        /// </summary>
        public static string MissionText2 {
            get {
                return ResourceManager.GetString("MissionText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Mission.
        /// </summary>
        public static string MissionTitle {
            get {
                return ResourceManager.GetString("MissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Cooperative - BBQCode.com : Cooperative web design and development.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shankle filet mignon beef ribs capicola bacon fatback. Sausage shank bacon meatloaf
        ///            chuck tenderloin. Capicola bresaola rump, tail filet mignon chuck fatback pancetta
        ///            salami pig andouille ground round tri-tip pork chop ham..
        /// </summary>
        public static string TextAlexisLerouxChartre {
            get {
                return ResourceManager.GetString("TextAlexisLerouxChartre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shankle filet mignon beef ribs capicola bacon fatback. Sausage shank bacon meatloaf
        ///            chuck tenderloin. Capicola bresaola rump, tail filet mignon chuck fatback pancetta
        ///            salami pig andouille ground round tri-tip pork chop ham..
        /// </summary>
        public static string TextElicNg {
            get {
                return ResourceManager.GetString("TextElicNg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shankle filet mignon beef ribs capicola bacon fatback. Sausage shank bacon meatloaf
        ///            chuck tenderloin. Capicola bresaola rump, tail filet mignon chuck fatback pancetta
        ///            salami pig andouille ground round tri-tip pork chop ham..
        /// </summary>
        public static string TextMartinFournier {
            get {
                return ResourceManager.GetString("TextMartinFournier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shankle filet mignon beef ribs capicola bacon fatback. Sausage shank bacon meatloaf
        ///            chuck tenderloin. Capicola bresaola rump, tail filet mignon chuck fatback pancetta
        ///            salami pig andouille ground round tri-tip pork chop ham..
        /// </summary>
        public static string TextSamuelPare {
            get {
                return ResourceManager.GetString("TextSamuelPare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shankle filet mignon beef ribs capicola bacon fatback. Sausage shank bacon meatloaf
        ///            chuck tenderloin. Capicola bresaola rump, tail filet mignon chuck fatback pancetta
        ///            salami pig andouille ground round tri-tip pork chop ham..
        /// </summary>
        public static string TextSimonGodbout {
            get {
                return ResourceManager.GetString("TextSimonGodbout", resourceCulture);
            }
        }
    }
}
