//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBQCode.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BBQCode.Resources.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured work.
        /// </summary>
        public static string FeaturedWork {
            get {
                return ResourceManager.GetString("FeaturedWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Members.
        /// </summary>
        public static string FootCoopMembers {
            get {
                return ResourceManager.GetString("FootCoopMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Mission.
        /// </summary>
        public static string FootCoopMission {
            get {
                return ResourceManager.GetString("FootCoopMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string FooterBlog {
            get {
                return ResourceManager.GetString("FooterBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find us.
        /// </summary>
        public static string FooterFindUs {
            get {
                return ResourceManager.GetString("FooterFindUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get in touch.
        /// </summary>
        public static string FooterGetInTouch {
            get {
                return ResourceManager.GetString("FooterGetInTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Cooperative.
        /// </summary>
        public static string FooterTheCooperative {
            get {
                return ResourceManager.GetString("FooterTheCooperative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Projects.
        /// </summary>
        public static string FootProjects {
            get {
                return ResourceManager.GetString("FootProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BBQCode.com - Home.
        /// </summary>
        public static string LogoTitleText {
            get {
                return ResourceManager.GetString("LogoTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BBQCode: Cooperative web design and development. See our projects and services, contact us..
        /// </summary>
        public static string MetaDescription {
            get {
                return ResourceManager.GetString("MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact us.
        /// </summary>
        public static string NavContactUs {
            get {
                return ResourceManager.GetString("NavContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the cooperative.
        /// </summary>
        public static string NavCoop {
            get {
                return ResourceManager.GetString("NavCoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string NavEn {
            get {
                return ResourceManager.GetString("NavEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fr.
        /// </summary>
        public static string NavFr {
            get {
                return ResourceManager.GetString("NavFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home.
        /// </summary>
        public static string NavHome {
            get {
                return ResourceManager.GetString("NavHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projects.
        /// </summary>
        public static string NavProjects {
            get {
                return ResourceManager.GetString("NavProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to services.
        /// </summary>
        public static string NavServices {
            get {
                return ResourceManager.GetString("NavServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BBQCode.com.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otherwise, you can call us at &lt;strong&gt;1-438-338-3095&lt;/strong&gt;..
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter update.
        /// </summary>
        public static string TwitterUpdate {
            get {
                return ResourceManager.GetString("TwitterUpdate", resourceCulture);
            }
        }
    }
}
